project:
  type: website
  output-dir: docs

website:
  title: "job-insights"
  navbar:
    left:
      - href: teste.qmd
        text: Home

format:
  revealjs:
    transition: slide
    transition-speed: fast
    slide-number: c/t
    footer: "First slides"
    theme: night

editor: visual

